### ISSUE TITLE
Web test/report 1

### ISSUE THREAD

**Issue by slybard** [UNFPAInnovation/SafePal_Web#1]
**Browsers/Devices:** *Chrome v. 54.0.2840.71, Microsoft Edge 25.10586.0.0, Microsoft Edge on Nokia Lumia 720, Chrome on Huawei Y360*

### **_bugs/solutions_**
- [x] Disable right-click on drop-down menu items on [index.php](http://52.43.152.73/index.php). Right now, they link to pages that do not look too good - like this one: http://52.43.152.73/reportingincidence.php
- [ ] Validation: No form validation for reporting forms. I managed to submit without entering or changing any data on the forms. Can also send form with empty phone number. 

### **_ui/ux_**
- [ ] Reports seem to have location but forms on index.php don't have option for location. 
- [ ] Increase font size on index.php to make it more legible. At least 16/17 px. This might require showing 2 rows with 2 columns of content each instead of 1 row with 4 columns. Or try tabs with [jQuery UI Tabs](https://jqueryui.com/tabs/). Would be easier to implement too, than hard-coded: 
```html
<a href="#" onclick="toggle_visibility('foo');">More/Less</a>
<div id="foo" style="display:none;">
```
which is currently applied to all 4 column divs.
- [x] When you hover over image to report a case, image **alt** text is "manage user levels". Perhaps, different **alt** text. 
- [ ] Add safepal favicon
- [ ] Remove "login into Safe Pal" link at bottom. Could be safer option to have this on an easy-to-remember sub-domain like https://dashboard.safepal.co or https://cso.safepal.co.
- [ ] Add SafePal/UNFPA copyright info and perhaps social media links to footer. Maybe link to **Ts & Cs** too
- [ ] 3 different partner columns on [connectwithus.php](http://52.43.152.73/connectwithus.php). Change formatting on page to just 2 columns. jQuery UI or [Masonry](http://masonry.desandro.com/) might provide a really fast implementation.
- [ ] Add simple contact us form to [connectwithus.php](http://52.43.152.73/connectwithus.php). This might work as a 3rd column on the page.
- [ ] SafePal logo/icon on [index.php](http://52.43.152.73/index.php) is stretched
- [ ] Increase font on [connectwithus.php](http://52.43.152.73/connectwithus.php) and [help.php](http://52.43.152.73/connectwithus.php)
- [ ] Need to re-align text in columns on [help.php](http://52.43.152.73/connectwithus.php)
- [ ] Might be good to brush up on font and alignment of report forms on index.php

### **_mobile_**
- [ ] **Not important but** could not access nav menu on small display - Huawei Y360

### **_misc_**
- [ ] General:
*Multiple typos in the copy on the website. 
*Change language/phrasing on reporting forms
- [ ] SEO stuff:
*Meta data tags
*Add nofollow attributes to all external <a> tags: 
```html
<a rel="nofollow" href="externallink.com">external link</a>
```
We don't want bots to think we are endorsing said external link.
- [ ] Security stuff: 
*Remove all credentials and authentication variables from current code base. Repo is public!
*Install SSL certificate
*Add some encryption and try for cleaner non-descriptive URLs
*Add noreferrer and noopener attributes to all <a> tags with "target='_blank'" to something like: 
```html
<a rel="noopener noreferrer" href="somelink.com">some link</a>
```
 *Good idea to remove links like this one which point to directory structure e.g. this one on reportingincidenceformyself.php:
```html
<link href="./calendar/css/default/calendar.css" rel="stylesheet" type="text/css" />
```

#### general
- [ ] Incident reports not validated so some empty fields/rows showing in dashboard

#### [dashboard.php](http://52.43.152.73/admin/dashboard.php)
- [ ] Corresponding number for each activity not accurate or updating. For example, there is one person under "Do not want to be contacted" but shows zero. After deleting some empty reports, value still remains "29" for notifications/new incidents

#### [user.php](http://52.43.152.73/admin/user.php)
- [ ] 'Empty' users . I think it is a validation issue wherever new users are created
- [ ] Gibberish user levels when you try to edit user levels
- [ ] Create & Update actions functional but not committed to system
- [ ] CRUD run without confirmation. For security purposes, confirmation should be with admin/user password

#### [levels.php](http://52.43.152.73/admin/levels.php)
- [ ] CRUD run without confirmation. For security purposes, confirmation should be with admin/user password

#### [cso.php](http://52.43.152.73/admin/cso.php)
- [ ] Cannot not edit cso data. Action non-functional
- [ ] CSOs have email addresses for status, instead of "active"/ "closed". Was the name of that column supposed to be different?
- [ ] CRUD run without confirmation. For security purposes, confirmation should be with admin/user password

#### [generalreports.php](http://52.43.152.73/admin/generalreports.php)
- [ ] Cannot generate PDFs

#### [settings.php](http://52.43.152.73/admin/settings.php)
- [ ] Cannot not edit location information
- [ ] Cannot access the page in Edge. Link seems to show here as "settings.php.php". 

#### general
- [ ] Similar issues as with the dashboard with filters, data validation etc. 
- [ ] Multiple typos in the dashboard copy
- [ ] Increase front and widen container div to make cases more legible. 

#### [incidents.php](http://52.43.152.73/cso/incidents.php)
- [ ] Cannot change status of "incidents"
- [ ]  "status" misspelt on "follow up" form

#### [assignments.php](http://52.43.152.73/cso/assignments.php)
- [ ] "View Details" action on works for "General Incidents and "Pushed/Cleared cases". And after that, cannot generate PDFs

**Comment by ewinkler** [comment]
Please separate these into individual issues so that we can track them better.

**Comment by wasswa** [comment]
separated
