### ISSUE TITLE
Increase font size on index.php

### ISSUE THREAD

**Issue by ewinkler** [UNFPAInnovation/SafePal_Web#11]
Increase font size on index.php to make it more legible. At least 16/17 px. This might require showing 2 rows with 2 columns of content each instead of 1 row with 4 columns. Or try tabs with jQuery UI Tabs. Would be easier to implement too, than hard-coded:
```
<a href="#" onclick="toggle_visibility('foo');">More/Less</a>
<div id="foo" style="display:none;">
```
which is currently applied to all 4 column divs.

**Comment by wasswa** [comment]
font increased
