### ISSUE TITLE
Security stuff

### ISSUE THREAD

**Issue by ewinkler** [UNFPAInnovation/SafePal_Web#23]
*Remove all credentials and authentication variables from current code base. Repo is public!
*Install SSL certificate
*Add some encryption and try for cleaner non-descriptive URLs
*Add noreferrer and noopener attributes to all tags with "target='_blank'" to something like:
```
<a rel="noopener noreferrer" href="somelink.com">some link</a>
```
*Good idea to remove links like this one which point to directory structure e.g. this one on reportingincidenceformyself.php:
```
<link href="./calendar/css/default/calendar.css" rel="stylesheet" type="text/css" />
```

**Comment by wasswa** [comment]
under review
