### ISSUE TITLE
Question on "Actions"

### ISSUE THREAD

**Issue by ewinkler** [UNFPAInnovation/SafePal_Web#5]
For “Actions” – would CSOs be entering the follow-up info/actions here, or does this intend to reflect the information entered by the user reporting the case? If the latter, it seems information cannot be updated, and now all the links (eg., “Details” or “Follow Up”) are functioning.

**Comment by wasswa** [comment]
On followup link under incidents the CSO can enter incident details NOT entered by the reporter
